#!/bin/sh

# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check copyright notice
files=`git diff --cached --name-only`
year=`date +%Y`

git rev-parse -q --verify MERGE_HEAD && \
    echo "Merge commit, skipping hooks" && exit 0

for f in $files; do
    head -10 $f | grep -i "Copyright (c)" 2>&1 1>/dev/null \
        || continue  # Copyright not present in this file
    if ! grep -i -e "$year NVIDIA CORPORATION" $f 2>&1 1>/dev/null; then
        need_update_year="$need_update_year $f"
    fi
    if ! grep -i -e " NVIDIA CORPORATION & AFFILIATES" $f 2>&1 1>/dev/null; then
        need_add_affiliates="$need_add_affiliates $f"
    fi
done
if [ -n "$need_add_affiliates" ]; then
    echo "'& AFFILIATES' is missing in the copyright notice of the following files, replacing:"
    for f in $need_add_affiliates; do
        echo "    $f"
        # NVIDIA CORPORATION. All rights reserved
        # ->
        # NVIDIA CORPORATION & AFFILIATES. All rights reserved
        sed -i 's/NVIDIA CORPORATION\. All rights reserved/NVIDIA CORPORATION \& AFFILIATES\. All rights reserved/' $f
        git add $f
    done
fi
if [ -n "$need_update_year" ]; then
    echo "$year is missing in the copyright notice of the following files, replacing:"
    for f in $need_update_year; do
        echo "    $f"
        # (c) 20\d\d, NVIDIA CORPORATION & AFFILIATES. All rights reserved
        # ->
        # (c) 20\d\d-20XX, NVIDIA CORPORATION & AFFILIATES. All rights reserved
        # where 20XX is current $year
        sed -E -i "s/\(c\) (20[[:digit:]][[:digit:]]) NVIDIA CORPORATION \& AFFILIATES\. All rights reserved/\(c\) \1-$year NVIDIA CORPORATION \& AFFILIATES\. All rights reserved/" $f
        # -20\d\d, NVIDIA CORPORATION & AFFILIATES. All rights reserved
        # ->
        # -20XX, NVIDIA CORPORATION & AFFILIATES. All rights reserved
        # where 20XX is current $year
        sed -i "s/-20[[:digit:]][[:digit:]] NVIDIA CORPORATION \& AFFILIATES\. All rights reserved/-$year NVIDIA CORPORATION \& AFFILIATES\. All rights reserved/" $f
        git add $f
    done
fi
exit 0
