image: nvidia/cuda:11.8.0-runtime-ubuntu20.04

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 20

stages:
    - build
    - test
    - deploy

.build:
    stage: build
    tags:
        - cuda
        - docker

.build:nvimagecodec:
    extends: .build
    artifacts:
        paths:
            - artifacts/
            - docs/sphinx/_build/html
        expire_in: 2 weeks
    script:
        - mkdir -p artifacts
        - export WHL_OUTDIR=$PWD/artifacts
        - mkdir -p build_docker
        - cd build_docker
        - source ../docker/build_helper.sh

build:nvimagecodec-cuda11:
    extends: .build:nvimagecodec
    image: gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/build-linux-x86_64:cuda-11.8.0-v1

build:nvimagecodec-cuda12:
    extends: .build:nvimagecodec
    image: gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/build-linux-x86_64:cuda-12.1.1-v1

.test:
    stage: test
    tags:
        - cuda
        - docker

.test:nvimagecodec:
    extends: .test
    script:
        - nvidia-smi
        - export CUDA_VERSION_MAJOR=$(echo "${CI_JOB_NAME}" | sed 's/.*cuda\([0-9]*\).*/\1/')
        - dpkg -i artifacts/nvimgcodecs-*-cuda${CUDA_VERSION_MAJOR}*lib.deb
        - dpkg -i artifacts/nvimgcodecs-*-cuda${CUDA_VERSION_MAJOR}*tests.deb
        - /opt/nvidia/nvimgcodecs/test/nvimgcodecs_tests --resources_dir /opt/nvidia/nvimgcodecs/resources

.test:nvimagecodec-python:
    extends: .test
    script:
        - nvidia-smi
        - export CUDA_VERSION_MAJOR=$(echo "${CI_JOB_NAME}" | sed 's/.*cuda\([0-9]*\).*/\1/')
        - python3 -m pip install artifacts/nvidia_nvimgcodecs_cuda${CUDA_VERSION_MAJOR}0-*.whl
        - pytest-3 test/test_python.py

test:nvimagecodec-cuda11:
    extends: .test:nvimagecodec
    image: nvidia/cuda:11.8.0-runtime-ubuntu20.04
    dependencies:
        - build:nvimagecodec-cuda11

test:nvimagecodec-cuda12:
    extends: .test:nvimagecodec
    image: nvidia/cuda:12.1.1-runtime-ubuntu20.04
    dependencies:
        - build:nvimagecodec-cuda12

test:nvimagecodec-python-cuda11:
    extends: .test:nvimagecodec-python
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-11.8.0-v1
    dependencies:
        - build:nvimagecodec-cuda11

test:nvimagecodec-python-cuda12:
    extends: .test:nvimagecodec-python
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-12.1.1-v1
    dependencies:
        - build:nvimagecodec-cuda12

# Documentation jobs
include: '.gitlab/ci/build_docs.yml'
