image: nvidia/cuda:11.8.0-runtime-ubuntu20.04

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 20
    WITH_DYNAMIC_NVJPEG: "ON"
    WITH_DYNAMIC_NPP: "ON"

stages:
    - build
    - test
    - deploy

.build:
    stage: build
    tags:
        - cuda
        - docker

.build:nvimagecodec:
    extends: .build
    artifacts:
        paths:
            - artifacts/
            - docs/sphinx/_build/html
        expire_in: 2 weeks
    script:
        - mkdir -p artifacts
        - export WHL_OUTDIR=$PWD/artifacts
        - mkdir -p build_docker
        - cd build_docker
        - source ../docker/build_helper.sh

build:cuda11.8:
    extends: .build:nvimagecodec
    variables:
        WITH_DYNAMIC_NVJPEG: "OFF"
        WITH_DYNAMIC_NPP: "OFF"
    image: gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/build-linux-x86_64:cuda-11.8-v3


build:cuda12.1:
    extends: .build:nvimagecodec
    image: gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/build-linux-x86_64:cuda-12.1-v3

build:cuda11.8-gcc9:
    extends: .build:nvimagecodec
    variables:
        WITH_DYNAMIC_NVJPEG: "OFF"
        WITH_DYNAMIC_NPP: "OFF"
    when: manual
    image: gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/build-linux-x86_64:cuda-11.8-gcc9-v3

.test:
    stage: test
    tags:
        - cuda
        - docker

.test:nvimagecodec:
    extends: .test
    script:
        - nvidia-smi
        - export CUDA_VERSION_MAJOR=$(echo "${CI_JOB_NAME}" | sed 's/.*cuda\([0-9]*\).*/\1/')
        - dpkg -i artifacts/nvimgcodec-*-cuda${CUDA_VERSION_MAJOR}*lib.deb
        - dpkg -i artifacts/nvimgcodec-*-cuda${CUDA_VERSION_MAJOR}*tests.deb
        - /opt/nvidia/nvimgcodec/test/nvimgcodec_tests --resources_dir /opt/nvidia/nvimgcodec/resources

.test:python:
    extends: .test
    script:
        - nvidia-smi
        - export CUDA_VERSION_MAJOR=$(echo "${CI_JOB_NAME}" | sed 's/.*cuda\([0-9]*\).*/\1/')
        - python3 -m pip install artifacts/nvidia_nvimgcodec_cuda${CUDA_VERSION_MAJOR}0-*.whl
        - pytest-3 -v test/test_python.py
        - pytest-3 -v test/test_decode_multichannel.py
        - pytest-3 -v test/test_decode_dtype.py

.test:transcode:
    extends: .test
    script:
        - nvidia-smi
        - export CUDA_VERSION_MAJOR=$(echo "${CI_JOB_NAME}" | sed 's/.*cuda\([0-9]*\).*/\1/')
        - dpkg -i artifacts/nvimgcodec-*-cuda${CUDA_VERSION_MAJOR}*lib.deb
        - dpkg -i artifacts/nvimgcodec-*-cuda${CUDA_VERSION_MAJOR}*tests.deb
        - pytest-3 -v /opt/nvidia/nvimgcodec/test/test_transcode.py

test:cuda11.3:
    extends: .test:nvimagecodec
    image: nvidia/cuda:11.3.1-runtime-ubuntu20.04
    dependencies:
        - build:cuda11.8

test:cuda11.8:
    extends: .test:nvimagecodec
    image: nvidia/cuda:11.8.0-runtime-ubuntu20.04
    dependencies:
        - build:cuda11.8

test:cuda12.1:
    extends: .test:nvimagecodec
    image: nvidia/cuda:12.1.1-runtime-ubuntu20.04
    dependencies:
        - build:cuda12.1

test:python-cuda11.3:
    extends: .test:python
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-11.3-v4
    dependencies:
        - build:cuda11.8

test:python-cuda11.8:
    extends: .test:python
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-11.8-v4
    dependencies:
        - build:cuda11.8

test:python-cuda12.1:
    extends: .test:python
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-12.1-v4
    dependencies:
        - build:cuda12.1

test:transcode-cuda11.3:
    extends: .test:transcode
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-11.3-v4
    dependencies:
        - build:cuda11.8

test:transcode-cuda11.8:
    extends: .test:transcode
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-11.8-v4
    dependencies:
        - build:cuda11.8

test:transcode-cuda12.1:
    extends: .test:transcode
    image:  gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvimagecodec/runner-linux-x86_64:cuda-12.1-v4
    dependencies:
        - build:cuda12.1

# Documentation jobs
include: '.gitlab/ci/build_docs.yml'
