image: gitlab-master.nvidia.com:5005/cuda-hpc-libraries/nvjpeg2k/build:native-x86_64-centos7-11.8-12.0

variables:
    GIT_SUBMODULE_STRATEGY: normal
    DEPENDENCIES_DIR: "$CI_PROJECT_DIR/.dependencies"
    CMAKE_URL: "https://github.com/Kitware/CMake/releases/download/v3.24.1/cmake-3.24.1-linux-x86_64.tar.gz"
    CMAKE_ROOT: "$CI_PROJECT_DIR/.dependencies/cmake"
    GTEST_GIT_URL: "https://github.com/google/googletest.git"
    GTEST_TAG: "release-1.10.0"
    GTEST_SOURCE_ROOT: "$CI_PROJECT_DIR/.dependencies/googletest"
    GTEST_ROOT: "$CI_PROJECT_DIR/.dependencies/gtest"


before_script:
  - export CUDACXX=/usr/local/cuda-11.8/bin/nvcc

.build:
    stage: build
    tags:
        - docker
        - cuda

.build:nvimagecodec:
    extends: .build
    artifacts:
        paths:
            - build/src/*.so.*
            - build/src/*.a
            - build/test/nvimagecodec_tests
            - build/test/nvimagecodec_tests_static
        expire_in: 2 weeks

build:nvjpeg2k:
    extends: .build:nvimagecodec

    script:
        # Get build type
        - source /etc/bashrc
        - source .gitlab/ci/build_type.sh
        # Build
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=NVIMAGECODEC_BUILD_TYPE ../.
        - nice -n 19 make -j8


# Documentation jobs
# include: '.gitlab/ci/build_docs.yml'

